name: Airqua_env
channels:
  - conda-forge
  - defaults
dependencies:
  - affine
  - aom
  - attrs
  - blas
  - blosc
  - bottleneck
  - branca
  - brotlicffi
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - cfitsio
  - cftime
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - colorama
  - contourpy
  - cycler
  - dav1d
  - expat
  - folium
  - fontconfig
  - fonttools
  - freeglut
  - freetype
  - freexl
  - fribidi
  - geopandas
  - geopandas-base
  - geos
  - geotiff
  - graphite2
  - h5py
  - harfbuzz
  - hdf4
  - hdf5
  - icu
  - idna
  - intel-openmp
  - jinja2
  - joblib
  - jpeg
  - kealib
  - kiwisolver
  - lcms2
  - lerc
  - libaec
  - libarchive
  - libavif
  - libboost
  - libcurl
  - libdeflate
  - libffi
  - libgdal
  - libglib
  - libiconv
  - libkml
  - libkrb5
  - libnetcdf
  - libpng
  - libpq
  - libspatialite
  - libssh2
  - libtiff
  - libwebp-base
  - libxml2
  - libzip
  - libzlib
  - lz4-c
  - mapclassify
  - markupsafe
  - matplotlib-base
  - minizip
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpi
  - mpi4py
  - netcdf4
  - networkx
  - numexpr
  - numpy
  - numpy-base
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pcre2
  - pillow
  - pip
  - pixman
  - poppler
  - poppler-data
  - proj
  - pycparser
  - pyogrio
  - pyparsing
  - pyproj
  - pysocks
  - python=3.12.12
  - python-dateutil
  - python-tzdata
  - pytz
  - qhull
  - rasterio
  - requests
  - scikit-learn
  - scipy
  - setuptools
  - shapely
  - six
  - sqlite
  - tbb
  - tbb-devel
  - threadpoolctl
  - tiledb
  - tk
  - tzdata
  - uriparser
  - urllib3
  - wheel
  - xarray
  - xerces-c
  - xyzservices
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
    - annotated-types==0.7.0
    - meteostat==1.7.6
    - pydantic==2.12.3
    - pydantic-core==2.41.4
    - pydantic-settings==2.11.0
    - python-dotenv==1.2.1
    - typing-extensions==4.15.0
    - typing-inspection==0.4.2