name: Airqua_env
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0=py312haa95532_0
  - aom=3.6.0=hd77b12b_0
  - attrs=24.3.0=py312haa95532_0
  - blas=1.0=mkl
  - blosc=1.21.6=h4190f5b_0
  - bottleneck=1.4.2=py312h4b0e54e_0
  - branca=0.8.1=py312haa95532_0
  - brotlicffi=1.0.9.2=py312h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.10.5=h4c7d964_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2025.10.5=py312haa95532_0
  - cffi=2.0.0=py312h02ab6af_0
  - cfitsio=3.470=h2bbff1b_7
  - cftime=1.6.4=py312h827c3e9_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=py312haa95532_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=pyhd3eb1b0_0
  - colorama=0.4.6=py312haa95532_0
  - contourpy=1.3.1=py312h214f63a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h2bbff1b_0
  - expat=2.7.1=h8ddb27b_0
  - folium=0.20.0=py312haa95532_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py312h02ab6af_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - freexl=2.0.0=hd7a5696_0
  - fribidi=1.0.10=h62dcd97_0
  - geopandas=1.1.1=py312haa95532_0
  - geopandas-base=1.1.1=py312haa95532_0
  - geos=3.10.6=he74ecf9_0
  - geotiff=1.7.0=hbf7d8e7_4
  - graphite2=1.3.14=hd77b12b_1
  - h5py=3.14.0=py312h6fc9867_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.14.5=ha36df97_2
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.7=py312haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - jinja2=3.1.6=py312haa95532_0
  - joblib=1.5.2=py312haa95532_0
  - jpeg=9e=h827c3e9_3
  - kealib=1.5.0=h6c4040a_2
  - kiwisolver=1.4.8=py312h5da7b33_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libaec=1.1.3=hcdb6601_0
  - libarchive=3.7.7=h9243413_0
  - libavif=1.1.1=h827c3e9_0
  - libboost=1.88.0=h3d2b97d_0
  - libcurl=8.15.0=h2300eb9_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libgdal=3.6.2=hdf1f3d4_10
  - libglib=2.84.2=h405b238_0
  - libiconv=1.16=h2bbff1b_3
  - libkml=1.3.0=h63940dd_7
  - libkrb5=1.21.3=h885b0b7_4
  - libnetcdf=4.9.3=h0c3980a_0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.6=h652a1e2_0
  - libspatialite=5.1.0=h6715bb4_2
  - libssh2=1.11.1=h2addb87_0
  - libtiff=4.7.0=h404307b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.8=h866ff63_0
  - libzip=1.8.0=h289538f_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mapclassify=2.10.0=py312haa95532_0
  - markupsafe=3.0.2=py312h827c3e9_0
  - matplotlib-base=3.10.6=py312h43afe63_0
  - minizip=4.0.3=hb68bac4_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py312h0b37514_0
  - mkl_fft=1.3.11=py312h5810407_1
  - mkl_random=1.2.8=py312h8683371_1
  - mpi=1.0=msmpi
  - mpi4py=4.0.3=py312h827c3e9_0
  - msmpi=10.1.1=had4844c_0
  - msys2-conda-epoch=20160418=1
  - netcdf4=1.7.2=py312hd3a5b52_2
  - networkx=3.5=py312haa95532_0
  - numexpr=2.11.0=py312ha02bb35_1
  - numpy=2.3.3=py312hc2e1e29_1
  - numpy-base=2.3.3=py312hc851d2b_1
  - openjpeg=2.5.2=h9b5d1b5_1
  - openssl=3.5.4=h725018a_0
  - packaging=25.0=py312haa95532_1
  - pandas=2.3.3=py312ha5e6156_0
  - pcre2=10.42=h0ff8eda_1
  - pillow=11.3.0=py312hb328d1f_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h4043f72_0
  - poppler=24.09.0=h10b5248_4
  - poppler-data=0.4.12=haa95532_0
  - proj=9.3.1=h4c8f42b_1
  - pycparser=2.23=py312haa95532_0
  - pyogrio=0.10.0=py312he5c4563_0
  - pyparsing=3.2.0=py312haa95532_0
  - pyproj=3.6.1=py312hcaa9d94_1
  - pysocks=1.7.1=py312haa95532_0
  - python=3.12.12=h716150d_1
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py312haa95532_0
  - qhull=2020.2=h59b6b97_2
  - rasterio=1.4.3=py312he5c4563_0
  - requests=2.32.5=py312haa95532_0
  - scikit-learn=1.7.2=py312h9296b3f_0
  - scipy=1.16.2=py312h86a6471_0
  - setuptools=80.9.0=py312haa95532_0
  - shapely=2.1.1=py312hbe77627_0
  - six=1.17.0=py312haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - threadpoolctl=3.5.0=py312hfc267ef_0
  - tiledb=2.3.3=hd8964de_3
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - uriparser=0.9.8=h1a0bd13_0
  - urllib3=2.5.0=py312haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - win_inet_pton=1.1.0=py312haa95532_0
  - xarray=2025.10.1=py312haa95532_0
  - xerces-c=3.2.4=hd77b12b_1
  - xyzservices=2025.4.0=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - annotated-types==0.7.0
      - meteostat==1.7.6
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydantic-settings==2.11.0
      - python-dotenv==1.2.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
prefix: C:\ProgramData\anaconda3\envs\Airqua_env
